name: deploy

on:
  push:
    branches:
      - CI/CD
  
jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images - Client
      uses: docker/build-push-action@v2
      with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest

    - name: Build and Push Docker Images - Server
      uses: docker/build-push-action@v2
      with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/server:latest

    - name: Build and Push Docker Images - Socket
      uses: docker/build-push-action@v2
      with:
          context: ./socket
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/socket:latest
    
    - name: login EC2 and depoly
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-northeast-1c

        ssh ec2-user@${{ secrets.EC2_IP }} 'cd project && cd chatroom && 'cd project && cd chatroom && 
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/server:latest
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/socket:latest
        docker-compose down
        docker-compose up -d
        '
